#!/usr/bin/env bash
#
# jsonv 0.1.0
# A Bash command line tool for converting JSON to CSV
#
# Copyright (c) 2013 Paul Engel, released under the MIT license
# https://github.com/archan937/jsonv.sh
#
# Get a JSON file
#
# Example (e.g. example.json)
#
#     [
#       {
#         "name": "Dagny Taggart",
#         "age": 39
#       }, {
#         "name": "Francisco D'Anconia",
#         "age": 40
#       }, {
#         "name": "Hank Rearden (a.k.a \"The Tank\")",
#         "age": 46
#       }
#     ]
#
# Command line usage
#
# Call `jsonv` and pass the paths of the values used for the CSV columns (comma separated).
# Optionally, you can pass a prefix for the paths as a second argument.
#
# Example
#
#     $ cat example.json | jsonv name,age
#     "Dagny Taggart",39
#     "Francisco D'Anconia",40
#     "Hank Rearden (a.k.a \"The Tank\")",46
#
#     $ cat example.json | jsonv name,age > example.csv
#     $ cat example.csv
#     "Dagny Taggart",39
#     "Francisco D'Anconia",40
#     "Hank Rearden (a.k.a \"The Tank\")",46
#

dir=$(cd `dirname $0` && pwd)

if [[ $dir =~ /\/bin$/ ]]; then
  sh=$dir/.jsonv/json.sh
  log=$dir/.jsonv/log
  tokens=$dir/.jsonv/tokens
  map=$dir/.jsonv/map
else
  sh=$dir/utils/json.sh
  log=$dir/tmp/log
  tokens=$dir/tmp/tokens
  map=$dir/tmp/map
fi

get_key () {
  echo $1 | xargs | awk -F. '{
    for (i = 1; i <= NF; i++) {
      if (i > 1) {
        printf ",";
      }
      printf "\""$i"\"";
    }
  }'
}

echo_log () {
  echo "[$(date +'%Y-%m-%d %H:%M:%S')] $1" >> $log
}

jsonv () {
  echo_log "Writing tokens file"
  cat /dev/stdin | $sh -b > $tokens

  echo_log "Deriving keys"
  keys=()
  for path in ${1//,/ }; do
    keys+=($(get_key $path))
  done

  echo_log "Deriving prefix"
  prefix=''
  if [ "$2" != "" ]; then
    prefix=$(get_key $2)","
    escaped_prefix=$(echo $prefix | sed 's/\"/\\"/g')
  fi

  echo_log "Counting entries"
  count=$(cat $tokens | sed 's/^[\["a-z,]*//g' | sed 's/,.*//g' | awk '/^[0-9]+$/ && !_[$0]++' | awk -F\t 'BEGIN{max==""} ($1 > max) {max=$1} END{print max}')

  echo_log "Writing map file"
  eval "> $map"
  for ((i=0; i<=$count; i++)); do
    for key in "${keys[@]}"; do
      printf "[$prefix$i,"$key"]\t" >> $map
    done
    echo >> $map
  done

  echo_log "Deriving line format"
  format=''
  for ((i=1; i<=${#keys[@]}; i++)); do
    if [ $i -gt 1 ]; then
      format+='","'
    fi
    format+="a[\$"$i"]"
  done

  echo_log "Compiling CSV output"
  program="'FNR==NR{a[\$1]=\$2; next} {print $format}'"
  eval "awk -F\\\t $program $tokens $map"

  echo_log "Removing tokens and map file"
  eval "rm $tokens; rm $map"

  echo_log "Done."
  echo "=====================" >> $log
}

if [ "$1" != "" ]; then
  jsonv $1 $2
fi